<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activo Inventariable ID' => '',
    'Caracteristica ID' => '',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Delete' => 'Eliminar',
    'ID' => '',
    'Infrastructure Asset Subcategory' => 'Subcategoría Activo Infraestructura',
    'Localidad' => '',
    'Name' => 'Nombre',
    'Nombre' => '',
    'Software Asset Subcategory' => 'Subcategoría Activo Software',
    'Space' => 'Espacio',
    'Space Number' => 'Numeración Espacio',
    'The selected feature is already being used by this asset' => 'La característica seleccionada ya está siendo usada por el activo',
    'The {modelClass} has been successfully deleted' => 'El {modelClass} ha sido eliminado correctamente',
    'Unable to delete the {modelClass} since it is being used in either some {modelClass2} or {modelClass3}' => 'No se puede borrar el {modelClass} porque está siendo usado por algún {modelClass2} o {modelClass3}',
    'Unable to delete the {modelClass} since it is being used in some {modelClass2}' => 'No se puede borrar el {modelClass} porque está siendo usado por algún {modelClass2}',
    'Units' => 'Unidades',
    'Update {modelClass}:' => 'Actualizar {modelClass}:',
    'purchase Price' => 'Precio de Compra',
    '{modelClass}' => '',
    '{modelClass} ' => '',
    'Asset Feature Values' => '@@Valores Características Activos@@',
    'Asset Name' => '@@Nombre@@',
    'El ' => '@@@@',
    'Feature' => '@@Característica@@',
    'Feature Name' => '@@Nombre@@',
    'Feature Units of Measurement' => '@@Unidades@@',
    'Incidents' => '@@Incidencias@@',
    'Inventoriable Asset' => '@@Activo Inventariable@@',
    'Purchase Price' => '@@Precio Compra@@',
    'Reports' => '@@Informes@@',
    'Software' => '@@Software@@',
    'Subcategory' => '@@Subcategoría@@',
    '- Select the {modelClass} -' => '- Selecciona el {modelClass} -',
    '- Select the {modelClass} where the {modelClass2} is located -' => '- Selecciona el {modelClass} donde está ubicado el {modelClass2} -',
    'Are you sure you want to delete this item?' => '¿Seguro que deseas eliminar este ojeto?',
    'Asset' => 'Activo',
    'Asset Feature Value' => 'Valor Característica Activo',
    'Asset Features Values' => 'Valores Características Activo',
    'Asset Number' => 'Número de serie',
    'Building' => 'Edificio',
    'Buildings' => 'Edificios',
    'Caracteristicas' => 'Features',
    'Create' => 'Crear',
    'Features' => 'Características',
    'Infrastructure Asset Subcategories' => 'Subcategorías Activo Infraestructura',
    'Infrastructure Assets' => 'Activos Infraestructura',
    'Purchase Date' => 'Fecha Compra',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Software Asset Subcategories' => 'Subcategorías Activo Software',
    'Software Assets' => 'Activos Software',
    'Spaces' => 'Espacios',
    'Update' => 'Actualizar',
];
