<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create and continue' => '',
    'Dashboard' => 'Panel de control',
    'Incidents' => 'Incidencias',
    'Inventory' => 'Inventario',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar sesión',
    'Reports' => 'Informes',
    'Reset' => '',
    'Users' => 'Usuarios',
    'The selected feature is already being used by this asset' => '@@La característica seleccionada ya está siendo usada por este activo@@',
    'The selected feature is already being used by this hardware element' => '@@La característica seleccionada ya está siendo usada por este elemento hardware@@',
    'Tipo Activo' => '@@@@',
    '- Select the asset type -' => 'Selecciona el tipo de activo',
    '- Select the {modelClass} -' => '- Selecciona el {modelClass} -',
    '- Select the {modelClass} where the {modelClass2} is located -' => '- Selecciona el {modelClass} donde está ubicado el {modelClass2} -',
    'Are you sure you want to delete this item?' => '¿Seguro que deseas eliminar este objeto?',
    'Asset' => 'Activo',
    'Asset Feature-Value' => 'Valor-Característica Activo',
    'Asset Features-Values' => 'Valores-Características Activo',
    'Asset Number' => 'Código',
    'Asset Type' => 'Tipo Activo',
    'Assets' => 'Activos',
    'Building' => 'Edificio',
    'Buildings' => 'Edificios',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Delete' => 'Eliminar',
    'Feature' => 'Característica',
    'Features' => 'Características',
    'Hardware' => 'Hardware',
    'Hardware Asset' => 'Activo Hardware',
    'Hardware Asset Configuration' => 'Configuración Activo Hardware',
    'Hardware Asset Subcategories' => 'Subcategorías Activo Hardware',
    'Hardware Asset Subcategory' => 'Subcategoría Activo Hardware',
    'Hardware Assets' => 'Activos Hardware',
    'Hardware Assets Configurations' => 'Configuraciones Activos Hardware',
    'Hardware Element' => 'Elemento Hardware',
    'Hardware Element Feature-Value' => 'Valor-Característica Elemento Hardware',
    'Hardware Element Features-Values' => 'Valores-Características Elemento Hardware',
    'Hardware Element Part' => 'Parte Elemento Hardware',
    'Hardware Element Parts' => 'Partes Elemento Hardware',
    'Hardware Element Subcategory' => 'Subcategoría Elemento Hardware',
    'Hardware Elements' => 'Elementos Hardware',
    'ID' => 'ID',
    'Infrastructure' => 'Infraestructura',
    'Infrastructure Asset' => 'Activo Infraestructura',
    'Infrastructure Asset Subcategories' => 'Subcategorías Activo Infraestructura',
    'Infrastructure Asset Subcategory' => 'Subcategoría Activo Infraestructura',
    'Infrastructure Assets' => 'Activos Infraestructura',
    'Manufacturer' => 'Marca/Fabricante',
    'Model' => 'Modelo',
    'Name' => 'Nombre',
    'No features availables' => 'No hay características disponibles',
    'No parts available' => 'No hay partes disponibles',
    'No software available' => 'No hay sofware disponible',
    'Parts' => 'Partes',
    'Purchase Date' => 'Fecha de Compra',
    'Purchase Price' => 'Precio de Compra',
    'Search' => 'Buscar',
    'Serial Number' => 'Número de Serie',
    'Software' => 'Software',
    'Software Asset' => 'Activo Software',
    'Software Asset Subcategories' => 'Subcategorías Activo Software',
    'Software Asset Subcategory' => 'Subcategoría Activo Software',
    'Software Assets' => 'Activos Software',
    'Space' => 'Espacio',
    'Space Number' => 'Espacio',
    'Spaces' => 'Espacios',
    'The selected {modelClass} is already being used by this {modelClass2}' => 'El {modelClass} seleccionado ya está siendo usado en este {modelClass2}',
    'The {modelClass} has been successfully deleted' => 'El {modelClass} ha sido eliminado correctamente',
    'Town/City' => 'Localidad',
    'Unable to delete the {modelClass} since it is being used in either some {modelClass2} or {modelClass3}' => 'No se puede eliminar el {modelClass} porque está siendo utilizado en algún {modelClass2} o en algún {modelClass3}',
    'Unable to delete the {modelClass} since it is being used in some {modelClass2}' => 'No se puede eliminar el {modelClass} porque está siendo utilizado en algún {modelClass2}',
    'Units' => 'Unidades',
    'Update' => 'Actualizar',
    'Update {modelClass}:' => 'Actualizar {modelClass}',
    'Value' => 'Valor',
    '{modelClass}:' => '{modelClass}:',
];
