<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- Select the {modelClass} -' => '',
    '- Select the {modelClass} where the {modelClass2} is located -' => '',
    'Activo Inventariable ID' => '',
    'Are you sure you want to delete this item?' => '',
    'Asset' => '',
    'Asset Feature Value' => '',
    'Asset Features Values' => '',
    'Asset Number' => '',
    'Building' => '',
    'Buildings' => '',
    'Caracteristica ID' => '',
    'Caracteristicas' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Delete' => '',
    'Features' => '',
    'ID' => '',
    'Infrastructure Asset Subcategories' => '',
    'Infrastructure Asset Subcategory' => '',
    'Infrastructure Assets' => '',
    'Localidad' => '',
    'Name' => '',
    'Nombre' => '',
    'Purchase Date' => '',
    'Reset' => '',
    'Search' => '',
    'Software Asset Subcategories' => '',
    'Software Asset Subcategory' => '',
    'Software Assets' => '',
    'Space' => '',
    'Space Number' => '',
    'Spaces' => '',
    'The selected feature is already being used by this asset' => '',
    'The {modelClass} has been successfully deleted' => '',
    'Unable to delete the {modelClass} since it is being used in either some {modelClass2} or {modelClass3}' => '',
    'Unable to delete the {modelClass} since it is being used in some {modelClass2}' => '',
    'Units' => '',
    'Update' => '',
    'Update {modelClass}:' => '',
    'Valor' => '',
    'Valor Caracteristica Activo Inventariables' => '',
    'purchase Price' => '',
    '{modelClass}' => '',
    '{modelClass} ' => '',
    '- Select the building where the space is located -' => '@@@@',
    '- Select the infrastructure asset subcategory -' => '@@@@',
    '- Select the software asset subcategory -' => '@@@@',
    '- Select the space where the asset is located -' => '@@@@',
    'Asset Feature Values' => '@@@@',
    'Asset Name' => '@@@@',
    'Create Asset Feature Value' => '@@@@',
    'Create Building' => '@@@@',
    'Create Feature' => '@@@@',
    'Create Incident' => '@@@@',
    'Create Infrastructure Asset' => '@@@@',
    'Create Infrastructure Asset Subcategory' => '@@@@',
    'Create Report' => '@@@@',
    'Create Software Asset' => '@@@@',
    'Create Software Asset Subcategory' => '@@@@',
    'Create Space' => '@@@@',
    'Create {modelClass} ' => '@@@@',
    'Create {modelClass}:' => '@@@@',
    'El ' => '@@@@',
    'Feature' => '@@@@',
    'Feature Name' => '@@@@',
    'Feature Units of Measurement' => '@@@@',
    'Incidents' => '@@@@',
    'Inventoriable Asset' => '@@@@',
    'Purchase Price' => '@@@@',
    'Reports' => '@@@@',
    'Software' => '@@@@',
    'Subcategory' => '@@@@',
    'Update {modelClass}' => '@@@@',
    'Update {modelClass} ' => '@@@@',
    'Update {modelClass}: ' => '@@@@',
];
